### ISSUE TITLE
Take over the Shoebill Project?

### ISSUE THREAD

**Issue by Huntman616** [pruten/shoebill#13]
Let me start off by saying sad it will be that you won't be able to work on Shoebill going forward. I really like the idea of Shoebill. I guess what I'm trying to say is can I take over the Shoebill project. I'm currently teaching myself how to code with the help of my uncle who is a computer teacher and some friends who code so I have  help if I need it. so as I was saying can I take over the Shoebill project since you won't be able to work on Shoebill going forward.

Thanks,
Huntman616

**Comment by ianfixes** [comment]
https://github.com/emaculation/macemu/issues/110

**Comment by ianfixes** [comment]
@pruten  I've sent you an invitation to join the [emaculation GItHub project](https://github.com/orgs/emaculation/people) as an admin, where I am modernizing the build systems (cross-platform Continuous Integration) for a variety of Macintosh emulation projects and utilities.  

Would you feel comfortable [transferring this repo](https://github.com/pruten/shoebill/settings) to that organization, so that we are able to continue the work?  My other option is to adopt one of the forks like the one @kanjitalk755 has updated.

**Comment by pruten** [comment]
Hi @ianfixes 

I appreciate the offer! I'm happy for anyone to attempt to take over the project -- right now there are 38 forks, but none seem to have lasted more than a few commits.  I'd like to retain my version for now (with its 204 precious stars), but by all means fork off a copy.  I can update readme.md to refer people to your fork, the new official repo.

**Comment by ianfixes** [comment]
That sounds great!  For all these emulation projects, the stars seem to be well-earned.  

As far as switching the README goes, let me get CI set up first.  Where can I find information on the build process / supported platforms / etc?
